using System.Collections.Generic;
using UnityEngine;

public class SwordManager : MonoBehaviour
{
    [SerializeField] private InputManager inputManager;

    [SerializeField] private Material materialToSwap;

    [SerializeField] private PlayerManager playerManager;
    [SerializeField] private BossManager bossManager;

    public AttackTypes attackState = AttackTypes.Idle;

    // i had this logic generated by claude so it might not be the best but essentially
    // what i want to do here is just know if the b button is freshly pressed instead
    // of holding it down to make parrying an actual challenge
    private bool bJustPressed = false;
    private bool bWasPressed = false;


    private class StanceModifier
    {
        int stanceType; // 0 -> fire, 1 -> ice, 2 -> lightning
        float stabModifier;
        float slashModifier;

    }

    //private List<StanceModifier> stanceModifiers = new()
    //{
    //    new StanceModifier(),
    //    new StanceModifier(),
    //    new StanceModifier(),
    //};

    private void OnEnable()
    {
        if (inputManager != null)
            inputManager.OnSwingComplete += SetAttackState;
    }

    private void OnDisable()
    {
        if (inputManager != null)
            inputManager.OnSwingComplete -= SetAttackState;
    }

    private void Update()
    {
        bool bIsPressed = inputManager.BButtonPressed();
        bJustPressed = bIsPressed && !bWasPressed;
        bWasPressed = bIsPressed;
    }

    public void SetStanceState(int stance)
    {
        switch (stance)
        {
            case 0: // 0 -> Fire

                materialToSwap.color = Color.red;
                break;
            case 1: // 1 -> Ice
                materialToSwap.color = Color.cyan;
                break;
            case 2: // 2 -> Lightning
                materialToSwap.color = Color.yellow;
                break;
            default:
                materialToSwap.color = Color.white;
                break;
        }        
    }

    private void SetAttackState(AttackTypes attack)
    {
        attackState = attack;
    }

    private void OnTriggerStay(Collider other)
    {
        if (other.CompareTag("Attack"))
        {
            if (bJustPressed)
            {
                Rigidbody rb = other.GetComponent<Rigidbody>();
                if (rb == null) return;

                rb.useGravity = false;

                Vector3 direction = (other.transform.position - transform.position).normalized;

                float speed = rb.linearVelocity.magnitude;
                if (speed < 5f) speed = 20f;

                rb.linearVelocity = direction * speed;
            }
        }
    }

}